git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  log:
    showGraph: always
gui:
    border: rounded
    nerdFontsVersion: "3"
    lightTheme: false
    theme:
      activeBorderColor:
        - '#98c379'
        - bold
      inactiveBorderColor:
        - '#5c6370'
      optionsTextColor:
        - '#61afef'
      selectedLineBgColor:
        - '#3e4451'
      cherryPickedCommitBgColor:
        - '#c678dd'
      cherryPickedCommitFgColor:
        - '#282c34'
      unstagedChangesColor:
        - '#e06c75'
      defaultFgColor:
        - '#abb2bf'
      searchingActiveBorderColor:
        - '#e5c07b'
